/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Labirent;

/**
 *
 * @author PC
 */
public class BitisEkrani extends javax.swing.JFrame {

    TembelSirin tembelSirin = new TembelSirin();
    GozlukluSirin gozlukluSirin = new GozlukluSirin();
    secimEkrani1 sEkrani1 = new secimEkrani1();

    /**
     * Creates new form BitisEkrani
     */
    public BitisEkrani(int x) {
        initComponents();
      /*  if (sEkrani1.getOzellik() == 0) {
            Skor.setText(String.valueOf(x));
        }
        if (sEkrani1.getOzellik() == 1) {
            Skor.setText(String.valueOf(x));
        }*/
       Skor.setText(String.valueOf(x));
        setTitle("Kazandınız");

        setSize(1920, 1080);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Skor = new javax.swing.JLabel();
        SkorText = new javax.swing.JLabel();
        ArkaPlan = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Skor.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        getContentPane().add(Skor);
        Skor.setBounds(740, 280, 120, 70);

        SkorText.setFont(new java.awt.Font("Tahoma", 1, 54)); // NOI18N
        SkorText.setText("SKORUNUZ");
        SkorText.setRequestFocusEnabled(false);
        getContentPane().add(SkorText);
        SkorText.setBounds(410, 280, 310, 70);

        ArkaPlan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/KAZANMA.jpg"))); // NOI18N
        ArkaPlan.setText("jLabel1");
        getContentPane().add(ArkaPlan);
        ArkaPlan.setBounds(-2, -9, 1970, 1100);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1978, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1102, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1978, 1102);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BitisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BitisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BitisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BitisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BitisEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArkaPlan;
    private javax.swing.JLabel Skor;
    private javax.swing.JLabel SkorText;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
